### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by iNakel** [DekuDesu/UnityShapefileAsync#3]
I can't get it to work after import a get a bunch of errors...

**Comment by artyredd** [comment]
Sorry about that! I'll take a look with a fresh scene and see what's going on.

**Comment by artyredd** [comment]
I pushed an update regarding the namespace error that was included in the main repo. Apparently when I bundled the files for github's initial commit I refactored a name and Visual Studio decided to replace the name in some files but not others. Give it a shot now and see if you have less errors. Keep in mind that MI Convex hull is a third party dependency for Mesh generation and will need to be acquired separately.

**Comment by iNakel** [comment]
That solved all the problems!

![Screen Shot 2021-03-11 at 16 19 10](https://user-images.githubusercontent.com/61609637/110856364-8d6e2800-8285-11eb-9ec5-0fc9cda3c298.png)
Even though I imported all the following repos I still get the following error:
"The name 'MIConvexHull' does not exist in the current context"

https://github.com/DesignEngrLab/MIConvexHull
https://github.com/gusmanb/MIConvexHull
https://github.com/nate-peters/SolidConvexHull

EDIT: By the way... a simple question on the go (since is hard to get in contact with you XD)
Does this repo support 3D shapefiles?

**Comment by artyredd** [comment]
Unfortunately this repo does not support 3d at this time only 2d maps. I recommend using **https://github.com/DesignEngrLab/MIConvexHull** for mesh generation as it is the only one i found that produced reliable mesh shapes.
